class Topics:
    POWER_STATUS = "/axon/system/power_status"
    AUDIO_STATUS = "/axon/system/audio_status"
    MIC_LEVEL = "/axon/audio/mic_level"
    TTS_REQUEST = "/axon/hri/tts_request"
    PWM_BATCH = "/axon/actuators/pwm/batch_cmd"
    PWM_STATUS = "/axon/actuators/pwm/status"
    SET_AUDIO_CONTROLS = "/axon/system/set_audio_controls"
    SET_PWM_BATCH = "/axon/actuators/pwm/set_batch"
    REQUEST_SHUTDOWN = "/axon/system/request_shutdown"
    SET_ROBOT_MODE = "/axon/system/set_robot_mode"
    SET_PAN_TILT = "/axon/actuators/set_pan_tilt"
    ROBOT_MODE = "/axon/system/robot_mode"
    AXON_HEALTH = "/axon/system/health"
    PAN_TILT_CMD = "/axon/actuators/pan_tilt_cmd"
